### PR TITLE
Add details of Lite3DP in README

### PR DESCRIPTION
**Pull request by Matej-Hajek**
###### Based on #5 
Updated README.
Includes the original license at the end.
Includes the ["FAQs"](https://github.com/alt-lite3dp/Lite3DP-S1#faqs).
Added useful links, and info from [Lite3DP crowdsupply](https://www.crowdsupply.com/lite3dp/lite3dp-3d-printer).

I don´t know if there is too much info, or if this type of info should be in a GitHub repo wiki (wiki could be useful). But in this README is like 99% of info about the project and printer.

### CODE REVIEW

**Comment by eduncan911** [comment]
Thanks for the submission!  However, it looks like you have been working on an outdated version - as I had already added a lot of info to the README.

Could you rebase, and resolve the conflicts?  You'll see the info I already had as well, to try and merge everything together.

Any updates to the README to add more text is ***very welcomed!**  I do not think it is too much at all.

**Comment by Matej-Hajek** [comment]
Resolved the conflict, but don't know where your version of the readme is.

**Comment by eduncan911** [comment]
> Resolved the conflict, but don't know where your version of the readme is.

When you update your fork, it automatically pulls in the latest changes - including the updated README.  You view the current release on the `main` branch:

https://github.com/alt-lite3dp/Lite3DP-S1/

It looks like you got it, and deleted a lot/moved things around.  I'm fine with revamping the whole README as nothing was there before us.

I added some links and a FAQs section to help a few people that have asked a lot in Discord and Reddit.

But, let me take a look of the published version before we merge.

**Comment by eduncan911** [comment]
Also, what is your Discord username?

**Comment by Matej-Hajek** [comment]
> When you update your fork, it automatically pulls in the latest changes

Just learned that😁
(+check discord)

**Comment by eduncan911** [comment]
I took a look.  I'll merge this for now as the number of changes I have are pretty large.

**Pull request merged**
